version: '3.3'
services:
    prometheus:
        build: './prometheus'
        container_name: 'prometheus'
        ports:
            - '9090:9090'
    web:
        build: './web-server'
        container_name: 'web'
        ports:
            - '80:80'
    grafana:
        build: './grafana'
        container_name: 'grafana'
        ports:
            - '3000:3000'
